- name: Add docker repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker
  yum:
    name: docker

- name: Add docker config file
  copy:
    src: docker
    dest: /etc/sysconfig/docker

